### ISSUE TITLE
Use vite's normalizePath for plugin compatibility on Windows

### ISSUE THREAD

**Issue by olemarius** [jacobclevenger/vite-plugin-generate-exports#1]
Paths gets incorrect on Windows, as mentioned here https://github.com/wheatjs/vaguer-generate-exports/issues/1 

I fixed this using a simple replace, but as mentioned by @patak you can use normalizePath https://discord.com/channels/804011606160703521/804439226439565333/826152444392112178

```js
import { normalizePath } from 'vite'
normalizePath('my/path')
```

More about normalizePath here https://vitejs.dev/guide/api-plugin.html#rollup-plugin-compatibility

**Comment by wheatjs** [comment]
Fixed via #2
